### PR TITLE
Fix/515 missing fixes from v3

### PR DESCRIPTION
**Pull request by FrogDevelopper**
Adding missing fixes done in branch 3.3 but not reported into v4.0
(issue #515 )

### CODE REVIEW

**Comment by FrogDevelopper** [comment]
@alvarosanchez 
Looks I didn't select the correct target for the branch (master)
What should be the target branch for fixes in v4.0 ?

**Comment by alvarosanchez** [comment]
master today is the branch for v4.0.x

The correct solution would be to merge up from 3.3.x up to 4.0.x. Is this PR doing that?

**Comment by FrogDevelopper** [comment]
> The correct solution would be to merge up from 3.3.x up to 4.0.x. Is this PR doing that?
this PR is cherry-picks of the missing fixes

**Comment by FrogDevelopper** [comment]
> master today is the branch for v4.0.x

I don't see any branch v4.0.x

**Pull request merged**
