### PR TITLE
Add configuration property to allow prefixing hashicorp vault keys

### LINKED ISSUE #291: Add HashiCorp Vault subpath support
### Feature description

Micronaut HashiCorp Vault supports structure of kv engine where applications secrets starts from engine root

Directory | Description
-- | --
/application | Configuration shared by all applications
/[APPLICATION_NAME] | Application-specific configuration
/application/[ENV_NAME] | Configuration shared by all applications for an active environment name
/ | Application-specific configuration for an active environment name

And there is no way to use secrets placed somewhere deeper in engine.

Creating secret engine for each project in companies with a lot of departments with a lot of projects will cause project hell in root of vault.

It would be great to add some optional property like `vault.client.path-prefix` where you can put smth like `[PROJECT_NAME]` or `[GROUP_NAME]/[PROJECT_NAME]/[SUBPROJECT_NAME]` with any level of depth 

Directory | Description
-- | --
[PATH_PREFIX]/application | Configuration shared by all applications
[PATH_PREFIX]/[APPLICATION_NAME] | Application-specific configuration
[PATH_PREFIX]/application/[ENV_NAME] | Configuration shared by all applications for an active environment name
[PATH_PREFIX]/ | Application-specific configuration for an active environment name

### PR DESCRIPTION
**Pull request by GavrilovSV**
This is a possible solution to resolve #291

### CODE REVIEW

**Comment by SergeyLadutko** [comment]
@GavrilovSV this is a very good idea.

**Comment by GavrilovSV** [comment]
@jameskleeh 
Could you pls check the latest commit?

**Comment by GavrilovSV** [comment]
@jameskleeh 
Hey, any updates on this? Out team is waiting for this feature, would be grateful if you could review the latest changes

**Comment by ivyazmitinov** [comment]
@graemerocher, could take a look at this issue, please? It becomes a bit stale, and really required by our teams

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
