### PR TITLE
build: master branch targeting Micronaut 4.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you investigate this failure?

**Comment by timyates** [comment]
Checking...  Seems to be some mapping issue, and some error handling issue...

Still investigating

**Comment by timyates** [comment]
I thought this might be an Optional binding issue, but the Optional fixes are in to the latest SNAPSHOT, and it still fails

It seems like the registration is not happening on this branch with Micronaut 4.0.0-SNAPSHOT, but it does on `master`

@graemerocher are we missing a module from core?

**Comment by sdelamo** [comment]
> I thought this might be an Optional binding issue, but the Optional fixes are in to the latest SNAPSHOT, and it still fails
> 
> It seems like the registration is not happening on this branch with Micronaut 4.0.0-SNAPSHOT, but it does on `master`
> 
> @graemerocher are we missing a module from core?

@graemerocher  [extracted a new module `discovery-core`](https://github.com/micronaut-projects/micronaut-core/pull/8235)

**Comment by alvarosanchez** [comment]
Currently blocked by https://github.com/micronaut-projects/micronaut-core/issues/8450

**Comment by alvarosanchez** [comment]
@timyates @sdelamo @graemerocher I could use some help of another set of eyes. There are test failures because this request:

```
11:49:38.876 [default-nioEventLoopGroup-63-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP POST to http://localhost:55698/eureka/apps/heartbeat-service
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - host: localhost:55698
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - connection: keep-alive
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 739
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - Request Body
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - {"instance":{"instanceId":"heartbeat-service:55699","app":"heartbeat-service","ipAddr":"127.0.0.1","port":{"@enabled":true,"$":55699},"securePort":{"@enabled":false,"$":0},"homePageUrl":"http://localhost:55699","statusPageUrl":"http://localhost:55699/health","healthCheckUrl":"http://localhost:55699/health","secureHealthCheckUrl":"https://localhost/health","vipAddress":"heartbeat-service","secureVipAddress":"heartbeat-service","countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"hostName":"localhost","status":"UP","leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":0,"lastRenewalTimestamp":0,"evictionTimestamp":0,"serviceUpTimestamp":0}}}
11:49:38.876 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
```

Is regarded as not valid:

```
11:49:38.889 [default-nioEventLoopGroup-63-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 400 from http://localhost:55698/eureka/apps/heartbeat-service
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - HTTP Client Response Received (400 Bad Request) for Request: POST http://localhost:55698/eureka/apps/heartbeat-service
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - date: Tue, 13 Dec 2022 10:49:38 GMT
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - connection: keep-alive
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 656
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - Response Body
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - {"JsonError":{"message":"Bad Request","_embedded":{"errors":{"ArrayList":[{"message":"instance.app: must not be blank"},{"message":"instance.countryId: must be greater than or equal to 1"},{"message":"instance.dataCenterInfo: must not be null"},{"message":"instance.hostName: must not be blank"},{"message":"instance.instanceId: must not be blank"},{"message":"instance.ipAddr: must not be blank"},{"message":"instance.secureVipAddress: must not be blank"},{"message":"instance.status: must not be null"},{"message":"instance.vipAddress: must not be blank"}]}},"_links":{"self":{"DefaultLink":{"href":"/eureka/apps/heartbeat-service","templated":false}}}}}
11:49:38.889 [default-nioEventLoopGroup-63-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
```

The JSON body is the same as what the master branch version (where tests are passing) is producing.

Server-side logs (in case they are meaningful):

```
11:49:38.880 [default-nioEventLoopGroup-62-2] TRACE i.m.h.server.netty.NettyHttpServer - Server localhost:55698 Received Request: POST /eureka/apps/heartbeat-service
11:49:38.880 [default-nioEventLoopGroup-62-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Request POST /eureka/apps/heartbeat-service
11:49:38.880 [default-nioEventLoopGroup-62-2] TRACE i.m.http.server.RouteExecutor - Matched route POST - /eureka/apps/heartbeat-service to controller class io.micronaut.discovery.eureka.$MockEurekaServer$Definition$Intercepted
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: IDLE) received demand: 2
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) release message from buffer to satisfy demand: 2
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) emitting next message: {"instance":{"instanceId":"heartbeat-service:55699","app":"heartbeat-service","ipAddr":"127.0.0.1","port":{"@enabled":true,"$":55699},"securePort":{"@enabled":false,"$":0},"homePageUrl":"http://localhost:55699","statusPageUrl":"http://localhost:55699/health","healthCheckUrl":"http://localhost:55699/health","secureHealthCheckUrl":"https://localhost/health","vipAddress":"heartbeat-service","secureVipAddress":"heartbeat-service","countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"hostName":"localhost","status":"UP","leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":0,"lastRenewalTimestamp":0,"evictionTimestamp":0,"serviceUpTimestamp":0}}}
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = BUFFERING). Calling context.read()
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) release message from buffer to satisfy demand: 1
11:49:38.882 [default-nioEventLoopGroup-62-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) complete. Calling onComplete()
```

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
